### ISSUE TITLE
Cannot import geojson_pydantic after 'pip install geojson-pydantic'

### ISSUE THREAD

**Issue by sebastiantimwagner** [developmentseed/geojson-pydantic#14]
Python version: `3.8.5`
Pip: `pip 20.2.3`
Virtualenv: `virtualenv 20.0.31`
Package version: `geojson-pydantic==0.2.1`
OS: `Ubuntu 18.04.5 LTS`
Pydantic: `pydantic==1.6.1`
Error message:
```
> import geojson_pydantic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/PATH/fresh-env/lib/python3.8/site-packages/geojson_pydantic-0.2.1-py3.8.egg/geojson_pydantic/__init__.py", line 5, in <module>
  File "/home/PATH/fresh-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 467, in get_distribution
    raise TypeError("Expected string, Requirement, or Distribution", dist)
TypeError: ('Expected string, Requirement, or Distribution', None)
```

**Comment by lossyrob** [comment]
Also experienced this; installing from source in my virtualenv provided a workaround, couldn't run down what exactly the issue is here though.

**Comment by drewbo** [comment]
@sebastiantimwagner @lossyrob can you both try: https://github.com/cogeotiff/rio-cogeo/issues/116#issuecomment-632438374 that's the most similar error/build process I could find

**Comment by lossyrob** [comment]
The same error did not occur with rio-cogeo, and the `pip install -U setuptools` suggested fix on that issue did not solve the problem for geojson_pydantic

**Comment by vincentsarago** [comment]
I'm going to closes this for now, please fee free to comment again if this is still happening
