### ISSUE TITLE
Incompatible with pydantic >= 2.4

### ISSUE THREAD

**Issue by void-rooster** [developmentseed/geojson-pydantic#155]
import fails with any pydantic version >= 2.4.

this succeeds:

```python
import geojson_pydantic
```
in this environment:
```
# packages in environment at /home/kpenner/mambaforge/envs/pydantic:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
geojson-pydantic          1.0.2              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pydantic                  2.3.0                    pypi_0    pypi
pydantic-core             2.6.3                    pypi_0    pypi
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.1.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```
import fails with this traceback:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kpenner/mambaforge/envs/pydantic/lib/python3.12/site-packages/geojson_pydantic/__init__.py", line 3, in <module>
    from .features import Feature, FeatureCollection  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/pydantic/lib/python3.12/site-packages/geojson_pydantic/features.py", line 7, in <module>
    from geojson_pydantic.base import _GeoJsonBase
  File "/home/kpenner/mambaforge/envs/pydantic/lib/python3.12/site-packages/geojson_pydantic/base.py", line 11, in <module>
    class _GeoJsonBase(BaseModel):
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_model_construction.py", line 173, in __new__
    complete_model_class(
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_model_construction.py", line 463, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/dev/pydantic/pydantic/main.py", line 549, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_generate_schema.py", line 448, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_generate_schema.py", line 680, in _generate_schema
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/dev/pydantic/pydantic/_internal/_generate_schema.py", line 518, in _model_schema
    fields_schema: core_schema.CoreSchema = core_schema.model_fields_schema(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: model_fields_schema() got an unexpected keyword argument 'extra_validator'
```
with this environment:
```
# packages in environment at /home/kpenner/mambaforge/envs/pydantic:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
geojson-pydantic          1.0.2              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pydantic                  2.6.3              pyhd8ed1ab_0    conda-forge
pydantic-core             2.16.3          py312h4b3b743_0    conda-forge
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                69.1.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```
This investigation was prompted by a failure when using a field serializer with a field that's a Point.

**Comment by void-rooster** [comment]
OK, an editable install from source works fine. Might be an issue with what's distributed by conda-forge.
