### ISSUE TITLE
TypeError: Object of type FeatureCollection is not JSON serializable

### ISSUE THREAD

**Issue by jossefaz** [developmentseed/geojson-pydantic#23]
Hi 

First of all thank you for building this fantastic library.
I tried to use it in one of my [project](https://github.com/jossefaz/gis-custom-layers-api) 
I use [FastAPI](https://fastapi.tiangolo.com/) with pydantic validations 

My pydantic model looks like [this](https://github.com/jossefaz/gis-custom-layers-api/blob/master/src/app/api/schemas.py) 

```python

from typing import Optional
from geojson_pydantic.features import FeatureCollection
from pydantic import BaseModel

class CustomLayer(BaseModel):
    is_public: Optional[bool] = False
    layer: FeatureCollection
```

And my route looks like [this](https://github.com/jossefaz/gis-custom-layers-api/blob/master/src/app/api/customlayers.py) 

```python 

@router.post("/", response_model=FeatureCollection, status_code=status.HTTP_201_CREATED)
async def create_item(payload: CustomLayer, access_token: Optional[str] = Header(None)):
    if not access_token:
        raise_401_exception()
    user = await check_user_credentials(access_token)
    if not user:
        raise_401_exception()
    layer_id = await customlayers_repository.create(payload, user)
    layer = await customlayers_repository.get_one(layer_id)
    if not layer:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                            detail=f"Problem occured during item creation")
    return layer.geojson

```

But when I run it I got some trouble with JSON serialization of the FeatureCollection Model.

Here is the TraceBack

```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
     result = await app(self.scope, self.receive, self.send)
   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
     return await self.app(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
     await super().__call__(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
     await self.middleware_stack(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
     raise exc from None
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
     await self.app(scope, receive, _send)
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
     await self.simple_response(scope, receive, send, request_headers=headers)
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
     await self.app(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
     await self.simple_response(scope, receive, send, request_headers=headers)
   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
     await self.app(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
     raise exc from None
   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
     await self.app(scope, receive, sender)
   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
     await route.handle(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
     await self.app(scope, receive, send)
   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
     response = await func(request)
   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
     raw_response = await run_endpoint_function(
   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
     return await dependant.call(**values)
   File "./app/api/customlayers.py", line 21, in create_item
     layer_id = await customlayers_repository.create(payload, user)
   File "./app/db/customlayers.py", line 9, in create
     query = CustomLayersTable.insert().values(geojson=json.dumps(payload.layer), user_id=user["user_id"], is_public=payload.is_public)
   File "/usr/local/lib/python3.8/json/__init__.py", line 231, in dumps
     return _default_encoder.encode(obj)
   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
     chunks = self.iterencode(o, _one_shot=True)
   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
     return _iterencode(o, 0)
   File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
     raise TypeError(f'Object of type {o.__class__.__name__} '
 TypeError: Object of type FeatureCollection is not JSON serializable

```

Is anybody have an idea on how I can fix this ?

**Comment by jossefaz** [comment]
I managed it by using the `.json()` method inherited from [BaseModel](https://pydantic-docs.helpmanual.io/usage/exporting_models/)
